ndd-app/static/js/agent_transport_add.js
ndd-app/static/js/booking_add.js
ndd-app/templates/agent_transport/agent_transport_add.html
ndd-app/templates/booking/booking_add.html

Fixed Add Container style booking/agent first in

Fixed style.

---

ndd-app/agent_transport/views/agent_transport_edit_view.py
ndd-app/templates/agent_transport/agent_transport_edit.html

Change *pickup_date* and *return_date* follow *date* when edit data.

Fixed edit agent_transport page

---

ndd-app/agent_transport/views/agent_transport_add_view.py
ndd-app/booking/views/booking_add_view.py
ndd-app/static/js/add_form.js
ndd-app/static/js/agent_transport_add.js
ndd-app/static/js/booking_add.js
ndd-app/templates/agent_transport/agent_transport_add.html
ndd-app/templates/booking/booking_add.html

Add search input in customer dropdown for filter customer choices in add page. [Booking]
@ipoobest  ทำต่อด้วยจ้า
- ส่วน agent-transport
- ถ้าแก้ style ได้ ก็ลองดู

Add search for filter customer dropdown in add page

---

ndd-app/agent_transport/forms.py
ndd-app/agent_transport/views/agent_transport_add_view.py
ndd-app/agent_transport/views/agent_transport_edit_view.py
ndd-app/agent_transport/views/agent_transport_update_view.py
ndd-app/booking/forms.py
ndd-app/booking/views/booking_add_view.py
ndd-app/booking/views/booking_edit_view.py
ndd-app/booking/views/booking_time_view.py
ndd-app/booking/views/booking_update_view.py
ndd-app/customer/views/customer_add_view.py
ndd-app/customer/views/customer_edit_view.py
ndd-app/templates/agent_transport/agent_transport_add.html
ndd-app/templates/agent_transport/agent_transport_edit.html
ndd-app/templates/booking/booking_add.html
ndd-app/templates/booking/booking_edit.html
ndd-app/templates/customer/customer_table.html

**Main**
- Remove whitespace when add and edit data
**Additional**
- Add edit agent field in edit page
- Change maxlength

Fix bug remove whitespace

---

ndd-app/booking/views/booking_add_view.py
ndd-app/templates/booking/booking_add.html

Add time field in container detail [Add page]

Add time field in container detail [Add page]

---

ndd-app/agent_transport/views/agent_transport_print_view.py
ndd-app/booking/views/booking_print_view.py
ndd-app/templates/booking/booking_edit.html
ndd-app/templates/booking/booking_time.html
ndd-app/templates/pdf_template/booking_time_template.html

- Fix condition to alert
- Fix time print template
- Fix align edit page
- Add session for print

Fix time page / Session print

---

ndd-app/ndd/settings.py

fix error MAX_NUMBER_FIELDS

---

ndd-app/agent_transport/views/agent_transport_edit_view.py
ndd-app/agent_transport/views/agent_transport_table_view.py
ndd-app/booking/views/booking_edit_view.py
ndd-app/booking/views/booking_table_view.py

Fix bug sort bookings

---

ndd-app/static/css/style-table.css
ndd-app/templates/agent_transport/agent_transport_edit.html
ndd-app/templates/agent_transport/agent_transport_table.html
ndd-app/templates/booking/booking_edit.html
ndd-app/templates/booking/booking_table.html

**Fill color on TR**
- Green: Finished work
- Blue: Unfinished work

Fill color TR cell

---

ndd-app/agent_transport/views/agent_transport_edit_view.py
ndd-app/agent_transport/views/agent_transport_table_view.py
ndd-app/booking/views/booking_edit_view.py
ndd-app/booking/views/booking_table_view.py

Show bookings today in first page.

Change condition to show bookings

---

ndd-app/static/css/style-edit-table.css
ndd-app/static/css/style_add_booking.css
ndd-app/static/js/agent_transport_add.js
ndd-app/static/js/booking_add.js
ndd-app/templates/agent_transport/agent_transport_add.html
ndd-app/templates/agent_transport/agent_transport_edit.html
ndd-app/templates/booking/booking_add.html
ndd-app/templates/booking/booking_edit.html

Add select container size
- Add page
- Edit page

Add dropdown select size in add & edit page

---

ndd-app/booking/views/export_xls_view.py
ndd-app/booking/views/utils.py
ndd-app/templates/agent_transport/agent_transport_edit.html
ndd-app/templates/booking/booking_edit.html

- Fix excel style
- Add color in booking_no field

Fix export excel

---

ndd-app/templates/pdf_template/booking_bw_template.html
ndd-app/templates/pdf_template/booking_full_template.html
ndd-app/templates/pdf_template/booking_fw_template.html
ndd-app/templates/pdf_template/booking_ndd_fac_ndd_template.html
ndd-app/templates/pdf_template/booking_ndd_fac_return_template.html
ndd-app/templates/pdf_template/booking_ndd_return_template.html
ndd-app/templates/pdf_template/booking_yard_ndd_template.html

Change paper size

---

ndd-app/agent_transport/views/agent_transport_add_view.py
ndd-app/agent_transport/views/agent_transport_edit_view.py
ndd-app/agent_transport/views/agent_transport_page_view.py
ndd-app/booking/views/authentication_view.py
ndd-app/booking/views/booking_add_view.py
ndd-app/booking/views/booking_edit_view.py
ndd-app/booking/views/booking_page_view.py
ndd-app/booking/views/export_xls_view.py
ndd-app/customer/views/customer_data_view.py
ndd-app/customer/views/customer_page_view.py
ndd-app/ndd/urls.py
ndd-app/static/css/style_table.css
ndd-app/static/js/app_agent_transport_table.js
ndd-app/static/js/app_booking_table.js
ndd-app/templates/agent_transport/agent_transport_add_page.html
ndd-app/templates/agent_transport/agent_transport_table_edit.html
ndd-app/templates/base.html
ndd-app/templates/booking/booking_add_page.html
ndd-app/templates/booking/booking_table_edit.html
ndd-app/templates/export.html
ndd-app/templates/login.html

- Use Vue with login and export page
- Change shipper name in edit page
- Add input name

Change login and export to vue / Edit shipper in table

---

ndd-app/booking/views/booking_add_view.py
ndd-app/static/css/style_add.css
ndd-app/static/js/app_booking_add.js
ndd-app/static/js/app_booking_table.js
ndd-app/templates/booking/booking_add_page.html
ndd-app/templates/booking/booking_table_edit.html

- Add more Container No. and Seal No. input
- Fix ID and input number in edit page.

Add container and seal no import work

---

ndd-app/booking/views/booking_time_export.py
ndd-app/booking/views/booking_time_view.py
ndd-app/static/js/app_booking_table.js

Change process add time fields

Fix get time timeout

---

ndd-app/agent_transport/views/agent_transport_delete_view.py
ndd-app/booking/views/booking_delete_view.py
ndd-app/summary/templatetags/parse_date.py
ndd-app/templates/customer/customer_detail.html
ndd-app/templates/pdf_template/summary_print_template.html
ndd-app/templates/summary/summary_invoice_details.html
requirements.txt

- Upgrade django to 2.2
- Fixed bug radio button
- Change parse date format
- Delete work -> Delete invoice detail -> Sum total

Upgrade django 2.2

---

ndd-app/agent_transport/views/agent_transport_add_view.py
ndd-app/static/js/app_agent_transport_add.js
ndd-app/templates/agent_transport/agent_transport_add_page.html

Add container field for add agent transport page.

Add container field

---

ndd-app/static/js/app_summary_chart_page.js
ndd-app/static/js/app_summary_month_details_page.js
ndd-app/static/js/app_summary_week_details_page.js
ndd-app/static/js/app_summary_year_details_page.js
ndd-app/templates/summary/summary_chart_page.html
ndd-app/templates/summary/summary_month_details_page.html
ndd-app/templates/summary/summary_week_details_page.html
ndd-app/templates/summary/summary_year_details_page.html

- Fix height chart
- Fix style chart
- Fix width cell table

Fix height and axis style chart / Fix width table detail

---

ndd-app/summary/views/summary_month_view.py
ndd-app/summary/views/summary_year_view.py

Change to filter by queryset (prevent customers have same name)

Fix bug filter sub_customer

---

ndd-app/templates/base.html
ndd-app/templates/login.html
ndd-app/templates/summary/summary_apll_invoice_details.html
ndd-app/templates/summary/summary_customer_custom_page.html
ndd-app/templates/summary/summary_evergreen_invoice_details.html
ndd-app/templates/summary/summary_form_setting_page.html
ndd-app/templates/summary/summary_invoice_details.html
ndd-app/templates/summary/summary_page.html
ndd-app/templates/summary/summary_week_details_page.html

Change icon (font awesome) to version 5.8.1

Upgrade Font Awesome version

---

ndd-app/summary/templatetags/result.py
ndd-app/templates/pdf_template/summary_print_template.html

Add method for sum total in summary print

Fix sum method for summary print template

---

ndd-app/static/js/app_summary_invoice_details.js
ndd-app/summary/views/summary_invoice_details_view.py
ndd-app/summary/views/summary_print_view.py
ndd-app/templates/agent_transport/agent_transport_table_edit.html
ndd-app/templates/pdf_template/summary_evergreen_print_template.html
ndd-app/templates/pdf_template/summary_print_template.html
ndd-app/templates/summary/summary_customer_custom_modal.html
ndd-app/templates/summary/summary_customer_custom_page.html
ndd-app/templates/summary/summary_invoice_details.html

- Add extra data in customer setting option.
- Add extra field in invoice detail page / view / print template.
- Refactor print view.
- Change condition for column width (print template).
- Add "Pickup" state in status option (Agent transport).
- Fix return total in compute (drayage / gate).

Add extra field

---

ndd-app/templates/pdf_template/summary_print_template.html

Fix width condition in print template.

Fix column width for print template

---

ndd-app/summary/views/summary_print_view.py
ndd-app/templates/pdf_template/summary_print_template.html

Get max length data for set column width.

Refactor condition for column width

---

ndd-app/templates/pdf_template/summary_print_template.html
ndd-app/templates/summary/summary_evergreen_invoice_details.html
ndd-app/templates/summary/summary_invoice_details.html

- Remove debug part.
- Change style color button choice in summary detail page.

Remove unused part / Color button (other charge) in summary detail page

---

ndd-app/static/js/app_summary_invoice_details.js
ndd-app/summary/views/summary_invoice_details_view.py
ndd-app/summary/views/summary_print_view.py
ndd-app/templates/pdf_template/summary_print_template.html
ndd-app/templates/summary/summary_apll_add_fields.html
ndd-app/templates/summary/summary_apll_invoice_details.html
ndd-app/templates/summary/summary_customer_custom_modal.html
ndd-app/templates/summary/summary_customer_custom_page.html
ndd-app/templates/summary/summary_invoice_details.html

- Add Vat field for APLL option.
- Compute gate total (gate + vat).
- Remove EXTRA field option.

Remove option / Add VAT field

---

ndd-app/static/js/app_summary_invoice_page.js
ndd-app/templates/summary/summary_invoice_page.html

- Show invoice selected active.

Invoice selected active

---

ndd-app/static/js/app_summary_invoice_details.js
ndd-app/templates/summary/summary_apll_invoice_details.html

- Delete unused parameter for delete function (bug) in APLL option.
- Add try catch charge for delete summary detail function(JS).

Fix bug delete work in APLL option

---

ndd-app/templates/summary/summary_apll_add_fields.html

Fix add field APLL bug

---

ndd-app/agent_transport/views/agent_transport_data_view.py
ndd-app/booking/views/authentication_view.py
ndd-app/booking/views/booking_data_view.py
ndd-app/booking/views/booking_time_export.py
ndd-app/static/css/style_table.css
ndd-app/static/js/app_booking_table.js
ndd-app/static/js/app_dashboard_page.js
ndd-app/summary/urls.py
ndd-app/summary/views/summary_week_view.py
ndd-app/templates/booking/booking_page.html
ndd-app/templates/dashboard.html
ndd-app/templates/export_time.html
ndd-app/templates/summary/summary_evergreen_invoice_work_list_modal.html
ndd-app/templates/summary/summary_invoice_work_list_modal.html

- Change time export
-- Form to modal in dashboard page
-- Filter by customer name and date
- Change condition get work list in summary page
-- Filter by date from date_start to today
-- Show color if work date not in week range
- Refactor / Ordering queryset

Export time modal

---

ndd-app/booking/views/booking_edit_view.py

Add condition for new choice (yard)
- Same 'NDD' choice

Fix bug save edit booking (yard_ndd & fac_ndd truck no)

---

ndd-app/agent_transport/views/agent_transport_data_view.py
ndd-app/booking/views/booking_data_view.py
ndd-app/booking/views/dashboard_view.py
ndd-app/static/js/app_dashboard_page.js
ndd-app/templates/agent_transport/agent_transport_table_data.html
ndd-app/templates/agent_transport/agent_transport_table_edit.html
ndd-app/templates/booking/booking_table_data.html
ndd-app/templates/booking/booking_table_edit.html
ndd-app/templates/dashboard.html
ndd-app/templates/export_modal.html

**New**
- Show weekly work by date selected
- Show not start works count
**Fix**
- Fix column width and font size (small)
- Fix dashboard page

Fix dashboard page

---

ndd-app/agent_transport/views/agent_transport_page_view.py
ndd-app/booking/views/booking_add_view.py
ndd-app/booking/views/booking_time_export.py
ndd-app/static/js/app_booking_add.js
ndd-app/static/js/app_dashboard_page.js
ndd-app/static/js/app_summary_invoice_details.js
ndd-app/summary/views/summary_invoice_details_view.py
ndd-app/summary/views/summary_print_view.py
ndd-app/templates/agent_transport/agent_transport_table_edit.html
ndd-app/templates/booking/booking_add_page.html
ndd-app/templates/booking/booking_table_edit.html
ndd-app/templates/export_time.html
ndd-app/templates/summary/summary_apll_add_fields.html
ndd-app/templates/summary/summary_evergreen_add_fields.html
ndd-app/templates/summary/summary_evergreen_invoice_work_list_modal.html
ndd-app/templates/summary/summary_invoice_details.html
ndd-app/templates/summary/summary_invoice_work_list_modal.html
ndd-app/templates/summary/summary_week_details_page.html

- Add order by remark (Checkbox)
- Filter time export by shipper
- Disabled option (cancel shipper) - Edit page
- Nextday option in add booking page
**Invoice detail - work list**
- Can click cell for select work (Add invoice detail)
- Invoice detail select all works
**APLL add data**
- Add remark field
- Change add data logic
- Clear field after add data (APLL and Evergreen)
**Time remark**
- Fix time remark bug (error)
- Save only 6.00 time work

Invoice detail select work / Add data / Time remark bug

---

ndd-app/static/css/style_add.css
ndd-app/static/css/style_summary.css
ndd-app/templates/agent_transport/agent_transport_add_page.html
ndd-app/templates/booking/booking_add_page.html

- Add max height for customer select: Add booking page
- Select scroll width (10px)

Add max height for customer select / Select scroll width

---

ndd-app/static/css/style_table.css
ndd-app/templates/agent_transport/agent_transport_table_data.html
ndd-app/templates/booking/booking_table_data.html

Change font size to 0.5rem for status button

Status button size

---

ndd-app/templates/agent_transport/agent_transport_table_data.html
ndd-app/templates/agent_transport/agent_transport_table_edit.html
ndd-app/templates/booking/booking_table_data.html
ndd-app/templates/booking/booking_table_edit.html
ndd-app/templates/booking/booking_table_time.html

Complete status: green color
Other: white color

Change color row status

---

ndd-app/agent_transport/urls.py
ndd-app/agent_transport/views/agent_transport_delete_view.py
ndd-app/agent_transport/views/agent_transport_edit_view.py
ndd-app/agent_transport/views/agent_transport_page_view.py
ndd-app/booking/urls.py
ndd-app/booking/views/booking_delete_view.py
ndd-app/booking/views/booking_edit_view.py
ndd-app/booking/views/booking_page_view.py
ndd-app/booking/views/booking_time_export.py
ndd-app/static/css/style_table.css
ndd-app/static/js/app_agent_transport_add.js
ndd-app/static/js/app_agent_transport_table.js
ndd-app/static/js/app_booking_table.js
ndd-app/templates/agent_transport/agent_transport_add_page.html
ndd-app/templates/agent_transport/agent_transport_page.html
ndd-app/templates/agent_transport/agent_transport_table_data.html
ndd-app/templates/agent_transport/agent_transport_table_edit.html
ndd-app/templates/booking/booking_add_page.html
ndd-app/templates/booking/booking_page.html
ndd-app/templates/booking/booking_table_data.html
ndd-app/templates/booking/booking_table_edit.html
ndd-app/templates/booking/booking_table_time.html
ndd-app/templates/export_time.html

**Filter work**
- Count work (except cancel work)
- API filter work
- Remove unused part
**Shipper text color**
- Add / edit text color for shipper name

Filter booking

---

ndd-app/static/js/app_agent_transport_table.js
ndd-app/static/js/app_booking_table.js
ndd-app/templates/agent_transport/agent_transport_table_data.html
ndd-app/templates/booking/booking_table_data.html

Change color for print check

---

ndd-app/agent_transport/views/agent_transport_data_view.py
ndd-app/agent_transport/views/agent_transport_page_view.py
ndd-app/static/css/style_table.css
ndd-app/static/js/app_agent_transport_table.js
ndd-app/static/js/app_booking_table.js
ndd-app/static/js/utility/variables.js
ndd-app/templates/agent_transport/agent_transport_table_data.html
ndd-app/templates/agent_transport/agent_transport_table_edit.html
ndd-app/templates/booking/booking_table_data.html
ndd-app/templates/booking/booking_table_edit.html

- Change order and separate agent work
- Change color for time (light yellow) and container (light green) field

Agent order and add color

---

ndd-app/static/css/style_table.css
ndd-app/static/js/app_agent_transport_table.js
ndd-app/static/js/app_booking_table.js
ndd-app/static/js/utility/variables.js
ndd-app/templates/agent_transport/agent_transport_table_data.html
ndd-app/templates/agent_transport/agent_transport_table_edit.html
ndd-app/templates/booking/booking_table_data.html
ndd-app/templates/booking/booking_table_edit.html
ndd-app/templates/booking/booking_table_time.html

Separate morning work by change color after work complete

Separate morning work / Change color after work complate

---

ndd-app/static/css/style_summary.css
ndd-app/static/js/app_summary_invoice_details.js
ndd-app/summary/urls.py
ndd-app/summary/views/cheque_data_view.py
ndd-app/summary/views/summary_invoice_details_view.py
ndd-app/summary/views/summary_invoice_view.py
ndd-app/templates/summary/summary_apll_invoice_details.html
ndd-app/templates/summary/summary_evergreen_invoice_details.html
ndd-app/templates/summary/summary_invoice_details.html
ndd-app/templates/summary/summary_invoice_page.html
ndd-app/templates/summary/summary_week_details_page.html

- Copy invoice and detail
- Copied work cannot change work status
- Hide export work button
- Fix bug order by remark
- Add order by week in cheque page

Copy invoice / Fix order by remark / Order by in cheque page

---

ndd-app/agent_transport/views/agent_transport_edit_view.py
ndd-app/booking/views/booking_edit_view.py
ndd-app/static/css/style_table.css
ndd-app/static/js/app_agent_transport_table.js
ndd-app/static/js/app_booking_add.js
ndd-app/static/js/app_booking_table.js
ndd-app/templates/agent_transport/agent_transport_table_edit.html
ndd-app/templates/booking/booking_table_edit.html

- Background input transparent in edit page.
- Edit principal field

Change input style / Can edit principal field

---

ndd-app/agent_transport/views/agent_transport_print_view.py
ndd-app/booking/views/booking_print_view.py
ndd-app/static/js/app_booking_table.js
ndd-app/templates/agent_transport/agent_transport_table_data.html
ndd-app/templates/booking/booking_table_data.html
ndd-app/templates/pdf_template/agent_transport_template.html
ndd-app/templates/pdf_template/booking_template.html

- Couple work template: filled another work_id
- Add new print template
- Update print modal
- Refactor (fix indent html file)

Add new print choice / Couple work

---

ndd-app/summary/views/summary_week_view.py
ndd-app/templates/summary/summary_evergreen_add_fields.html

- Add field data (Evergreen invoice detail work)
- Fix bug remark week detail

Change logic for add field evergreen work

---

ndd-app/static/js/app_agent_transport_table.js
ndd-app/static/js/app_booking_table.js

Fix bug missing function (getShipper for filter work)

Add function getShipper (Bug)

---

ndd-app/booking/urls.py
ndd-app/booking/views/booking_data_view.py
ndd-app/booking/views/booking_print_view.py
ndd-app/customer/views/customer_data_view.py
ndd-app/static/css/style_pdf.css
ndd-app/static/js/app_agent_transport_table.js
ndd-app/static/js/app_booking_table.js
ndd-app/templates/agent_transport/agent_transport_page.html
ndd-app/templates/booking/booking_page.html
ndd-app/templates/booking/booking_table_data.html
ndd-app/templates/pdf_template/booking_template.html

- API check work_id
- Get shipper_address by work_id
- Update print modal (Add select address 2)
- Print view -> get shipper_address 2
- Print template -> show shipper_address 2
- Fix bug filter work
-- empty principal
-- reset shipper when change principal

Add address couple work

---

ndd-app/summary/views/cheque_data_view.py

Not count container (copy work)

Count container except copy work

---

ndd-app/static/js/app_agent_transport_table.js
ndd-app/static/js/app_booking_table.js
ndd-app/templates/agent_transport/agent_transport_page.html
ndd-app/templates/booking/booking_page.html

Fill booking_no or remark or date

Filter field required condition

---

ndd-app/templates/booking/booking_add_page.html

In add booking page (nextday work)

Add min-width to date field

---

ndd-app/summary/views/cheque_data_view.py

Filter by empty date_accept field

Fix cheque overdue filter

---

ndd-app/static/css/style_customer.css
ndd-app/static/js/app_commission_page.js
ndd-app/summary/serializers.py
ndd-app/summary/urls.py
ndd-app/summary/views/commission_view.py
ndd-app/summary/views/summary_page_view.py
ndd-app/summary/views/summary_week_view.py
ndd-app/templates/base.html
ndd-app/templates/dashboard.html
ndd-app/templates/summary/commission_page.html
ndd-app/templates/summary/summary_month_details_page.html

- API for get commission data
- Filter by customer
- Filter by date or work(NDD/VTS) or work_type(ep/fc)
- Permission

Commission page

---

ndd-app/employee/views/employee_page_view.py
ndd-app/static/js/app_commission_page.js
ndd-app/summary/views/summary_page_view.py
ndd-app/templates/summary/commission_page.html

- Loading when get data
- Add permission require 'employee.change_salary'

Add loading mode / Add permission require

---

ndd-app/employee/views/employee_page_view.py
ndd-app/static/js/app_commission_page.js
ndd-app/static/js/utility/filters.js
ndd-app/templates/employee/employee_page.html

**Commission page**
- Get week when reload page
**Employee page**
- Change side nav title
- Fix tel and account format filter

Refactor employee page / commission

---

ndd-app/static/js/app_commission_page.js
ndd-app/templates/pdf_template/summary_evergreen_print_template.html
ndd-app/templates/pdf_template/summary_print_template.html
ndd-app/templates/summary/commission_page.html

**Summary**
- Fix page-break bud in summary print template
**Commission**
- Cannot click other customer choices when loading (Get commission data)

Fix bug summary invoice print template

---

ndd-app/summary/views/summary_print_view.py
ndd-app/templates/summary/summary_evergreen_invoice_details.html

- Remove count line in summary print view

Refactor: Remove unused part

---

ndd-app/booking/views/booking_print_view.py
ndd-app/templates/base.html
ndd-app/templates/booking/booking_page.html
ndd-app/templates/booking/booking_table_data.html
ndd-app/templates/dashboard.html
ndd-app/templates/pdf_template/booking_template.html

- Add work order template for REUSE case
- Refactor Navbar expand in base

REUSE case work order template

---

ndd-app/summary/views/summary_report_export.py

Update summary report template

---

ndd-app/summary/views/summary_report_export.py

Replace special char for export file name

---

ndd-app/static/js/app_agent_transport_add.js
ndd-app/static/js/app_booking_add.js
ndd-app/templates/agent_transport/agent_transport_add_page.html
ndd-app/templates/booking/booking_add_page.html
ndd-app/templates/pdf_template/booking_template.html

**2 container case** (Normal work)
- Use seal_no field for container_2 in template [ cont_1 - cont_2 ]
- Hide Seal no field in template
**Limit works** (Normal & Agent Transport work)
- Limit add work quantity (max 150 works)
- Limit add work with container no (max 150 works)

2 container in normal work case & Limit add works

---

ndd-app/booking/admin.py
ndd-app/booking/models.py
ndd-app/booking/urls.py
ndd-app/booking/views/booking_time_export.py
ndd-app/booking/views/booking_time_view.py

**Booking time format**
- Remove booking time old format fields
- Remove copy and delete data API

Remove old format field / Remove copy and delete data API

---

ndd-app/templates/pdf_template/summary_print_template.html
ndd-app/templates/summary/summary_apll_invoice_details.html

- Add condition for APLL print template
- Print button

Print APLL Summary

---

ndd-app/agent_transport/views/agent_transport_add_view.py
ndd-app/agent_transport/views/agent_transport_edit_view.py
ndd-app/agent_transport/views/agent_transport_print_view.py
ndd-app/static/js/app_agent_transport_add.js
ndd-app/templates/agent_transport/agent_transport_add_page.html
ndd-app/templates/agent_transport/agent_transport_table_data.html
ndd-app/templates/agent_transport/agent_transport_table_edit.html
ndd-app/templates/pdf_template/agent_transport_template.html

- Fix work order in print template
- Change print work order form
- Change add page template
- Fix operation option

Fix Agent Transport Work Page (Work Order)

---

ndd-app/transport_report/admin.py

Fix bug expense summary date admin

---

ndd-app/static/js/app_transport_report_modal.js
ndd-app/templates/transport_report/transport_report_modal.html
ndd-app/truck/views/truck_data_view.py

**Transport Report**
- Auto fill status trip (E/F)
**Truck & Chassis**
- Order chassis by number (type Number)

Auto fill trip report

---

ndd-app/static/js/app_transport_report_modal.js

Set new object (Add new report)

Fix reset report detail (create new report)

---

ndd-app/transport_report/views/transport_report_data_view.py

Fix date range (Filter report data)

Fix report date range

---

ndd-app/static/css/style_transport_report.css
ndd-app/static/js/app_transport_report_daily_report_page.js
ndd-app/static/js/app_transport_report_expense_page.js
ndd-app/static/js/app_transport_report_modal.js
ndd-app/static/js/app_transport_report_yearly_report_page.js
ndd-app/static/js/utility/functions.js
ndd-app/templates/agent_transport/agent_transport_page.html
ndd-app/templates/transport_report/transport_report_daily_report_page.html
ndd-app/templates/transport_report/transport_report_expense_page.html
ndd-app/templates/transport_report/transport_report_expense_table.html
ndd-app/templates/transport_report/transport_report_expense_thead.html
ndd-app/templates/transport_report/transport_report_expense_upper.html
ndd-app/templates/transport_report/transport_report_filter_modal.html
ndd-app/templates/transport_report/transport_report_modal.html
ndd-app/templates/transport_report/transport_report_summary_page.html
ndd-app/transport_report/serializers.py
ndd-app/transport_report/urls.py
ndd-app/transport_report/views/transport_report_data_view.py

**UI**
- Sticky clear date row (Expense report page)
- Upper part
- Edit toggle button
- Column check button (Multiselect)
- Multiselect event (onclick)
- Pagination
- Total expense row (daily report page)
**API / Back end**
- Pagination
- Booking no 2 (Double container)
- Filter by booking no
- Refactor
- New: Get report by ID list
- New: Get default driver (& truck) data
- Update: Get daily report & get driver daily report

Improve report app

---

ndd-app/static/css/style_transport_report.css
ndd-app/static/js/app_transport_report_daily_report_page.js
ndd-app/static/js/app_transport_report_expense_page.js
ndd-app/static/js/app_transport_report_modal.js
ndd-app/static/js/app_transport_report_total_expense_page.js
ndd-app/static/js/app_transport_report_total_truck_page.js
ndd-app/static/js/utility/functions.js
ndd-app/summary/views/summary_month_view.py
ndd-app/templates/transport_report/transport_report_daily_report_page.html
ndd-app/templates/transport_report/transport_report_expense_table.html
ndd-app/templates/transport_report/transport_report_expense_thead.html
ndd-app/templates/transport_report/transport_report_expense_upper.html
ndd-app/templates/transport_report/transport_report_filter_modal.html
ndd-app/templates/transport_report/transport_report_modal.html
ndd-app/templates/transport_report/transport_report_total_expense_page.html
ndd-app/templates/transport_report/transport_report_total_truck_page.html
ndd-app/transport_report/serializers.py
ndd-app/transport_report/urls.py
ndd-app/transport_report/views/transport_report_data_view.py
ndd-app/transport_report/views/transport_report_edit_view.py
ndd-app/truck/views/truck_data_view.py

**New**
- Copy to clipboard: Total expense & Total truck page
- Editable table: Daily expense page
- Edit remark, price (work, allowance, overnight) fields
- API edit work_order list
- Filter by customer, empty price fields
**Change**
- Change total button: Total expense page
- Move `multiselect` method to global function
- Move `setPageRange` method to computed
**Fix Bug**
- Calculate decimal (parse decimal to float)
--------------------------------------------------------
- Order weekly summary by week field (number)

Improve transport report (2)
